services:
  - type: web
    name: accessibility-analyzer-backend
    env: node
    rootDir: backend
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    plan: free
    envVars:
      - key: PORT
        value: 10000
